name: Android8 Docker Build

on:
  push:
    branches:
      - release/android/openjdk8
  workflow_dispatch:

env:
  IMAGE_NAME: fastcurve/android-java-react:openjdk-

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set commit short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set Date Tag
        id: date_tag
        run: echo "tag_date=$(date +'%d-%m-%y')" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.android.openjdk8
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}${{ env.tag_date }}-${{ env.SHORT_SHA }}
            ${{ env.IMAGE_NAME }}latest